### ISSUE TITLE
[Request] Dirge of Cerberus support improvement

### ISSUE THREAD

**Issue by swosho** [Surihix/WhiteBinTools#4]
Incidentally, Dirge of Cerberus: FF7 has essentially the same setup with its filelist.bin ToC & kel.dat binary as FF13-1 (some of the files have some sort of additional encryption though). However, WhiteBinTools seems to fail at parsing the filenames/paths for the majority of the ToC's entries, same as the other FF13-1 unpacking solutions.
Can you please look into improving the compatibility with Dirge of Cerberus? Thank you.

Here's a zip with the crash log, decompressed file list, and vanilla JP filelist.bin: [dirgeofcerberus_jp_whitebintools.zip](https://github.com/Surihix/WhiteBinTools/files/11578368/dirgeofcerberus_jp_whitebintools.zip)

**Comment by Surihix** [comment]
The reason why it doesn't work is cause some of the virtual filepath strings are not present after the position and the size string. my tool assumes that there is always a valid filepath string after the position and the size strings. if you use my tool's filepaths unpacking feature and see the text file that you would get on using this feature, you will see what I mean (see the attached text file). 

I am assuming even the other unpacking tools, work with the same assumption that the path strings are always present and indicate a valid path. there isn't a system in place to skip processing empty path strings. I can try and see whether the unpacking issues with such null paths can be fixed or not. this will be implemented in a separate tool just for Dirge Cerberus as this WhiteBinTools was made with some core assumptions in the code that only apply to the ff13 trilogy's files.

[FILELIST.txt](https://github.com/Surihix/WhiteBinTools/files/11581346/FILELIST.txt)

**Comment by swosho** [comment]
Ah, my bad! I derped and focused too much on the file list included in the archive instead of the header one. Now I've actually noticed that far from every file included in the filelist.bin's decompressed ToC is even referenced in the file.txt list included in the binary, and there's no option to match the paths between the two by anything other than the listed sizes, so no dice.
Giving the pathless files sort of `%05d.dat` names based on the entry's number in the ToC would be a fine solution, I suppose...
But yeah, huge thanks for looking into this!

**Comment by Surihix** [comment]
While doing some code refactoring, I have managed to add in support for Dirge of Cerberus's archive file into WhiteBinTools.
At the time of writing this reply, all valid unpacking functions supported by this tool works for Dirge's archive file and these functions along with the repacking functions will all be available in the upcoming 1.5 version of WhiteBinTools.

**Comment by Surihix** [comment]
Support for Dirge of Cerberus is now added in v1.5.
